controller_list:
  - name: stackit_robot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_pan_joint
      - base_lift_joint
      - elbow_flex_joint
      - wrist_flex_joint
      - dummy_a_joint

